services:
  app:
    build: .
    container_name: YummyControlServer
    # 設定ファイルの注入
    volumes:
      - ./settings/config.json:/app/settings/config.json:ro # :ro Read Only
    environment:
      - PYTHONUNBUFFERED=1
